name: Publicar Documentação

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache das dependências MkDocs
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ hashFiles('**/requirements-docs.txt') }}
          path: ~/.cache/pip
          restore-keys: mkdocs-material-

      - name: Instalar MkDocs e tema Material
        run: |
          pip install mkdocs-material

      - name: Publicar no GitHub Pages
        run: mkdocs gh-deploy --force
